// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST_AI_MusicShop2.Models;

#nullable disable

namespace ST_AI_MusicShop2.Migrations
{
    [DbContext(typeof(MusicShopDbContext))]
    [Migration("20241020075402_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ST_AI_MusicShop2.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Album");
                });

            modelBuilder.Entity("ST_AI_MusicShop2.Models.CD", b =>
                {
                    b.HasBaseType("ST_AI_MusicShop2.Models.Album");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CD");
                });

            modelBuilder.Entity("ST_AI_MusicShop2.Models.DigitalAlbum", b =>
                {
                    b.HasBaseType("ST_AI_MusicShop2.Models.Album");

                    b.Property<double>("DigitalScore")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("DigitalAlbum");
                });

            modelBuilder.Entity("ST_AI_MusicShop2.Models.Vinyl", b =>
                {
                    b.HasBaseType("ST_AI_MusicShop2.Models.Album");

                    b.Property<int>("Edition")
                        .HasColumnType("int")
                        .HasColumnName("Vinyl_Edition");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("Vinyl_Size");

                    b.HasDiscriminator().HasValue("Vinyl");
                });
#pragma warning restore 612, 618
        }
    }
}
